language: python
python:
  - "3.6"

services:
  - docker

env:
  global:
    - SERVICE_UUID=f0ff9742-f626-41db-9ac3-631a3071e257
    - AOS_UPLOAD_SERVICE_URL=https://aoscloud.io:10000/api/v1/services/versions/
    - SP_CERTIFICATE=meta_folder/sp-client.pem
    - PRIVATE_KEY=meta_folder/private_key.pem

install:
  - pip install docker-compose
  - sudo apt-get install curl
  - mkdir package

script:
  - docker pull alekseibuziuma/aos_signer:1.0.0
  - docker run -v $(pwd)/meta_folder:/data/meta/ -v $(pwd)/src/:/data/src/ -v $(pwd)/package:/data/package alekseibuziuma/aos_signer:1.0.0
  - curl --request POST -k --cacert meta_folder/rootCA.crt.pem --cert $SP_CERTIFICATE --key $PRIVATE_KEY --form "service=$SERVICE_UUID" --form "file=@package/service.tar.gz" $AOS_UPLOAD_SERVICE_URL



